### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by chenxi456** [brainiac19/SuperStarInfoFetch#5]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\python\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\python\lib\concurrent\futures\process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "D:\python\lib\concurrent\futures\process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 866, in get_course_info_of_type
    return self._works_proc(course_id, get_detail)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 509, in _works_proc
    for works_of_page in futures:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 342, in _request_by_dict
    return post_process_func(eval(eval_string), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 573, in _works_list_page_proc
    item.update(next(futures))
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 322, in _get_url
    return post_process_func(self._session.get(url), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 594, in _work_proc
    parsed['questions'] = self._question_sections_parser(soup)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 729, in _question_sections_parser
    parsed = self._question_parser(question)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 747, in _question_parser
    question_dict.update(self._fill_question_parser(question))
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 834, in _fill_question_parser
    question_dict['score'] = self._norm_str(score.text)
AttributeError: 'NoneType' object has no attribute 'text'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\chajian\SuperStarInfoFetch-main\easyExample.py", line 19, in <module>
    result = ss.get_courses_info_by_name(['tasks', 'chapters', 'discussions', 'works', 'exams'],
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 897, in get_courses_info_by_name
    for (course_id, info_type), result in zip(id_type_combinations, futures):
  File "D:\python\lib\concurrent\futures\process.py", line 567, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by brainiac19** [comment]
现在试试？

**Comment by chenxi456** [comment]
> 现在试试？

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\python\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\python\lib\concurrent\futures\process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "D:\python\lib\concurrent\futures\process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 880, in get_course_info_of_type
    return self._works_proc(course_id, get_detail)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 509, in _works_proc
    for works_of_page in futures:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 342, in _request_by_dict
    return post_process_func(eval(eval_string), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 573, in _works_list_page_proc
    item.update(next(futures))
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 322, in _get_url
    return post_process_func(self._session.get(url), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 594, in _work_proc
    parsed['questions'] = self._question_sections_parser(soup)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 729, in _question_sections_parser
    parsed = self._question_parser(question)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 747, in _question_parser
    question_dict.update(self._fill_question_parser(question))
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 820, in _fill_question_parser
    for my_answer_elem, correct_answer_elem in zip(my_answers.find_all('dd'), correct_answers.find_all('dd')):
AttributeError: 'itertools.repeat' object has no attribute 'find_all'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\chajian\SuperStarInfoFetch-main\easyExample.py", line 19, in <module>
    result = ss.get_courses_info_by_name(['tasks', 'chapters', 'discussions', 'works', 'exams'],
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 911, in get_courses_info_by_name
    for (course_id, info_type), result in zip(id_type_combinations, futures):
  File "D:\python\lib\concurrent\futures\process.py", line 567, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
AttributeError: 'itertools.repeat' object has no attribute 'find_all'
是不是设置了反爬

**Comment by brainiac19** [comment]
啊 没 代码逻辑问题

**Comment by brainiac19** [comment]
我毕业年级了 学习通里没啥东西了 不好测试

**Comment by brainiac19** [comment]
修复

**Comment by chenxi456** [comment]
> 我毕业年级了 学习通里没啥东西了 不好测试
我的给你可以吗

**Comment by brainiac19** [comment]
后面有解决不了的问题的话再说吧 现在应该没问题了

**Comment by chenxi456** [comment]
如果没有考试，他会报错吗？这是我没有考试时候的报错输入手机号15956160296
输入密码1q2w3e4r
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\python\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\python\lib\concurrent\futures\process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "D:\python\lib\concurrent\futures\process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 886, in get_course_info_of_type
    return self._works_proc(course_id, get_detail)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 509, in _works_proc
    for works_of_page in futures:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 342, in _request_by_dict
    return post_process_func(eval(eval_string), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 573, in _works_list_page_proc
    item.update(next(futures))
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 322, in _get_url
    return post_process_func(self._session.get(url), *args)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 594, in _work_proc
    parsed['questions'] = self._question_sections_parser(soup)
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 711, in _question_sections_parser
    info_dissected = re.search(r'(.+)\.\s*(.+)（共(\d+)题，(\d+)分', section_info.text)  # 一. 简答题（共1题，100分）
AttributeError: 'NoneType' object has no attribute 'text'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\chajian\SuperStarInfoFetch-main\easyExample.py", line 19, in <module>
    result = ss.get_courses_info_by_name(['tasks', 'chapters', 'discussions', 'works', 'exams'],
  File "D:\chajian\SuperStarInfoFetch-main\SuperStarNew.py", line 917, in get_courses_info_by_name
    for (course_id, info_type), result in zip(id_type_combinations, futures):
  File "D:\python\lib\concurrent\futures\process.py", line 567, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "D:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'text'

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月27日 0:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [brainiac19/SuperStarInfoFetch] 运行报错 (Issue #5)


后面有解决不了的问题的话再说吧 现在应该没问题了

―

**Comment by chenxi456** [comment]
真的很抱歉多次打扰你

**Comment by brainiac19** [comment]
这个是考试里面没有题目吗

**Comment by brainiac19** [comment]
并且issue是公开的 你回复中包含了你的账号密码

**Comment by chenxi456** [comment]
> 并且issue是公开的 你回复中包含了你的账号密码

我知道，你那边留一下，我这就删除，这个是目前没有考试，也没有待考的考试

**Comment by brainiac19** [comment]
没有考试是不会出问题的 我再看看

**Comment by chenxi456** [comment]
> 没有考试是不会出问题的 我再看看

账号密码你需要吗

**Comment by brainiac19** [comment]
到我邮箱wuyuqi_tim@qq.com

**Comment by chenxi456** [comment]
> 到我邮箱[wuyuqi_tim@qq.com](mailto:wuyuqi_tim@qq.com)

请问收到了吗

**Comment by brainiac19** [comment]
收到了 我不太理解 学习通页面看课程数量不是很多， 脚本显示有很多课

**Comment by brainiac19** [comment]
哦我看到了 文件夹

**Comment by chenxi456** [comment]
> 哦我看到了 文件夹
好的

**Comment by brainiac19** [comment]
[5a3b65a](https://github.com/brainiac19/SuperStarInfoFetch/commit/5a3b65ac5790cc76151380b62ede6c7e5598ab8c)
实测用你的账号是没问题了

**Comment by brainiac19** [comment]
你课太多了 默认的在线打开方式可能会卡 建议下个vs code 搭配json editor插件 
默认获取所有课程的全部5种信息，建议仔细读一下文档，只获取需要的类型。

**Comment by chenxi456** [comment]
> 你课太多了 默认的在线打开方式可能会卡 建议下个vs code 搭配json editor插件 默认获取所有课程的全部5种信息，建议仔细读一下文档，只获取需要的类型。
好的

**Comment by brainiac19** [comment]
...我真是佛了 我又跑了一遍又报错

**Comment by brainiac19** [comment]
小问题 修了

**Comment by chenxi456** [comment]
你那边可以完美运行了是吗

**Comment by brainiac19** [comment]
目前最新版本 你的账号 不报错了

**Comment by chenxi456** [comment]
那就我电脑这边的问题了

**Comment by brainiac19** [comment]
还是可以发出来看一下 环境变量也有可能是原因

**Comment by chenxi456** [comment]
首先是在VS code安装python拓展报错import"request"could not be resolved from source pyance (reportMissingModuleSource)运行easy
Traceback (most recent call last):
  File "d:\chajian\SuperStarInfoFetch\easyExample.py", line 4, in <module>
    from SuperStarNew import SuperStar
  File "d:\chajian\SuperStarInfoFetch\SuperStarNew.py", line 11, in <module>
    import js2py
ModuleNotFoundError: No module named 'js2py

**Comment by brainiac19** [comment]
奥 这些确实都是你的问题 依赖没装好

**Comment by brainiac19** [comment]
参见requirements.txt 里面的模块全要先pip install上

**Comment by brainiac19** [comment]
还有个numpy也是需要的

**Comment by brainiac19** [comment]
然后vscode 如果只是需要用json查看器的话 不需要python相关的东西

**Comment by brainiac19** [comment]
那就是你的安装位置不在PATH里。网上找一下python找不到包这个问题

**Comment by brainiac19** [comment]
还有我记得之前提交的报错都是正常运行后的运行时报错了 怎么现在还会有找不到包的问题

**Comment by chenxi456** [comment]
> 还有我记得之前提交的报错都是正常运行后的运行时报错了 怎么现在还会有找不到包的问题

是email那个模块吗？没事了，哪个也是我自己问题

**Comment by chenxi456** [comment]
> 那就是你的安装位置不在PATH里。网上找一下python找不到包这个问题

删除重装永远的神

**Comment by brainiac19** [comment]
试一下有没有问题 确认没问题就close了

**Comment by chenxi456** [comment]
请问你方便远程看一下问题所在吗？Traceback (most recent call last):
  File "d:\chajian\SuperStarInfoFetch\easyExample.py", line 16, in <module>
    result = ss.get_course_info_by_name(course_count=3)
AttributeError: 'SuperStar' object has no attribute 'get_course_info_by_name'. Did you mean: 'get_courses_info_by_name'?

**Comment by chenxi456** [comment]
解决了

**Comment by chenxi456** [comment]
自己测试建了一个考试，没有找到考试卷子的内容

**Comment by brainiac19** [comment]
考试开始前不会拿到url，开始后也无法不触发计时拿到页面。将会跳过进行中的考试。
